AWSTemplateFormatVersion : '2010-09-09' 
Description: A hello world application. 
Resources: 
   HelloWorldFunction: 
     Type: AWS::Lambda::Function    
     Properties:       
       Handler: index.handler 
       Runtime: nodejs6.10 
       Code: 
         S3Bucket: ch2-sms-sam-test
         S3Key: index.zip 
       FunctionName: ch2-sms-sam-test
       Role: arn:aws:iam::300813158921:role/ch2-sms-lambda-role
   HelloWorldSubscription:
     Type: AWS::SNS::Subscription
     Properties: 
       Endpoint: arn:aws:lambda:us-west-2:300813158921:function:ch2-sms-sam-test
       Protocol: lambda
       TopicArn: arn:aws:sns:us-west-2:300813158921:ch2-sms-test
   HelloWorldPermission:
     Type: AWS::Lambda::Permission
     Properties:
      FunctionName:
        Fn::GetAtt:
        - HelloWorldFunction
        - Arn
      Action: lambda:InvokeFunction
      SourceArn: arn:aws:sns:us-west-2:300813158921:ch2-sms-test
      Principal: sns.amazonaws.com
     DependsOn:
       - HelloWorldFunction